import os
import re

def parse_concept_markdown(markdown_text):
    """
    Parses concept.md to extract metadata.
    """
    lines = markdown_text.split('\n')
    title = ""
    subtitle = ""
    concept_lines = []
    goal_lines = []
    paper_title = ""
    paper_url = ""
    
    current_section = "concept"
    
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('# '):
            title = stripped[2:]
            continue
        elif stripped.startswith('## '):
            heading = stripped[3:]
            if heading.lower() == 'objective':
                current_section = "objective"
            elif heading.lower() in ('publication', 'seminal publication'):
                current_section = "publication"
            else:
                subtitle = heading
            continue
            
        if current_section == "concept":
            concept_lines.append(line)
        elif current_section == "objective":
            goal_lines.append(line)
        elif current_section == "publication":
            if stripped:
                if not paper_title:
                    paper_title = stripped
                elif not paper_url:
                    paper_url = stripped

    return {
        "title": title,
        "subtitle": subtitle,
        "concept": '\n'.join(concept_lines).strip(),
        "goal": '\n'.join(goal_lines).strip(),
        "paperTitle": paper_title,
        "paperUrl": paper_url
    }

def get_template_and_solution(solution_code):
    """
    Parses solution.py.
    Solution code is the entire code, stripping '# <<< PRACTICE' and '# >>>' lines.
    Template code is generated by replacing anything between '# <<< PRACTICE' and '# >>>' with a 'pass'.
    """
    lines = solution_code.split('\n')
    solution_lines = []
    template_lines = []
    
    in_practice = False
    practice_indent = ""
    
    for line in lines:
        # Match practice markers
        if '# <<< PRACTICE' in line:
            in_practice = True
            # Find indentation of the marker line
            m = re.match(r'^(\s*)', line)
            practice_indent = m.group(1) if m else ""
            template_lines.append(f"{practice_indent}# Write your code here")
            template_lines.append(f"{practice_indent}pass")
            continue
        elif '# >>>' in line:
            in_practice = False
            continue
            
        # Build solution (omit marker lines)
        solution_lines.append(line)
        
        # Build template
        if not in_practice:
            template_lines.append(line)
            
    return {
        "solution": '\n'.join(solution_lines),
        "template": '\n'.join(template_lines)
    }

def load_tutorials():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tutorials_dir = os.path.join(base_dir, 'tutorials')
    if not os.path.exists(tutorials_dir):
        # Fallback to absolute path
        tutorials_dir = '/home/soda/src/bio-showcase/tutorials'
        
    chapters = []
    if not os.path.exists(tutorials_dir):
        return chapters
        
    folders = sorted([f for f in os.listdir(tutorials_dir) if os.path.isdir(os.path.join(tutorials_dir, f))])
    
    for idx, folder in enumerate(folders, 1):
        folder_path = os.path.join(tutorials_dir, folder)
        concept_path = os.path.join(folder_path, 'concept.md')
        solution_path = os.path.join(folder_path, 'solution.py')
        
        if os.path.exists(concept_path) and os.path.exists(solution_path):
            with open(concept_path, 'r', encoding='utf-8') as f:
                concept_md = f.read()
            with open(solution_path, 'r', encoding='utf-8') as f:
                solution_py = f.read()
                
            metadata = parse_concept_markdown(concept_md)
            code_variants = get_template_and_solution(solution_py)
            
            chapters.append({
                "id": idx,
                "folder_name": folder,
                "title": metadata["title"],
                "subtitle": metadata["subtitle"],
                "concept": metadata["concept"],
                "goal": metadata["goal"],
                "paperTitle": metadata["paperTitle"],
                "paperUrl": metadata["paperUrl"],
                "template": code_variants["template"],
                "solution": code_variants["solution"],
            })
            
    return chapters
