# Generated by Django 5.2.1 on 2025-05-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField()),
                ('seq_start', models.IntegerField()),
                ('seq_end', models.IntegerField()),
                ('result', models.CharField()),
            ],
        ),
    ]
